//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Script.Serialization;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int amount { get; set; }
        public int categoryId { get; set; }

        [ForeignKey("categoryId"), ScriptIgnore]
        public Category Category { get; set; }
    }
}
